---
anomaly_checks: prophet
audit: true
before_action_method: current_admin!
check_schedules:
- 1 day
- 1 hour
- 5 minutes
data_sources:
  main:
    url: <%= ENV["BLAZER_DATABASE_URL"] %>
    use_transaction: false
forecasting: prophet
from_email: dorian@dorianmarie.com
time_zone: Europe/Paris
user_class: User
user_method: current_user
user_name: to_s
