---
dispatchers:
- batch_size: 500
  polling_interval: 0.1
workers:
- queues: "scheduling"
  threads: <%= Integer(ENV.fetch("SOLID_QUEUE_SCHEDULING_THREADS") { ENV.fetch("SOLID_QUEUE_THREADS", 50) }) %>
- queues: "*"
  threads: <%= Integer(ENV.fetch("SOLID_QUEUE_DEFAULT_THREADS") { ENV.fetch("SOLID_QUEUE_THREADS", 50) }) %>
